baseurl = "https://www.alexledger.net/"
title = "Alex's Notes and Blog"
theme = "hugo-blog-awesome"
LanguageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true


[params]
  sitename = "Alex Ledger"
  defaultColor = "auto"
  toc = true
  mainSections = ["posts"]
  guideSections = ["guides"]
  intro = true
  headline = "Alex's Notes and Blog"
  description = "A collection of blog posts and notes"
  opengraph = true
  dateFormat = "Mon, Jan 2, 2006"
  params = true
  rss = true

[params.author]
  # avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Alex Ledger"
  name = "Alex Ledger"
  # description = ""
  description = "I build small projects and big projects, work on big problems and small problems, and love experimenting with old and new technologies."

[Author]
  name = "Alex Ledger"
  profile = "/page/about"

[Permalinks]
  post = "/:year/:month/:day/:filename/"

[Taxonomies]
  tag = "tags"

[[menu.main]]
name = "Posts"
pageRef = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
name = "Guides"
pageRef = "Guides"
url = "/guides/"
weight = 20

[[menu.main]]
name = "Tags"
pageRef = "Tags"
url = "/tags/"
weight = 30

[markup]
  [markup.highlight]
    # set markup.highlight.noClasses=false to enable code highlight
    noClasses = false
  [markup.goldmark.renderer]
    # Allow HTML in md files
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>