baseurl = "https://notes.alexledger.net/"
title = "Alex's Notes"
theme = "ghostwriter"
paginate = 50

[Params]
  mainSections = ["post"]
  intro = true
  headline = "Alex's Notes and Blog"
  description = "A collection of blog posts and notes"
  github = "https://github.com/aled1027"
  opengraph = true
  dateFormat = "Mon, Jan 2, 2006"
  params = true
  rss = true

[Author]
  name = "Alex Ledger"
  profile = "/page/about"

[Permalinks]
  post = "/:year/:month/:day/:filename/"

[Taxonomies]
  tag = "tags"

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "About"
url = "/page/about/"
weight = 3

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files